version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on: [redis]
    environment:
      REDIS_URL: redis://redis:6379/0

  worker:
    build: ./worker
    depends_on: [redis]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # ONLY worker needs Docker
    environment:
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:7-alpine
